version: "3.9"

services:
  tailscale-real:
    build: .
    container_name: tailscale-real
    privileged: true
    tty: true
    environment:
      - TS_AUTHKEY=tskey-auth-your-key-here  # ðŸ‘ˆ 
    ports:
      - "8888:8888"
